// Copyright 29-Dec-2021 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

/// Arr[OOBet *].

#ifndef DATA_BET_AOOBET_H
  #define DATA_BET_AOOBET_H

#include "dmc/Arr.h"
#include "data/Bet/OOOBet.h"

#include "data/Bet/OOBet.h"

/// Arr[OOBet *].
struct aOOBet_AOOBet {
  OOBet **es; // Start elements.
  OOBet **end; // End elements. (Elements are between 'es' (inclusive) and 'end'
              // exclusive.
  OOBet **endbf; // End buffer.
};

/// Arr[OOBet *].
typedef struct aOOBet_AOOBet AOOBet;

/// Creates a new Array with buffer size of 15 elements.
AOOBet *aOOBet_new (void);

/// 'buffer' must be > 0.
AOOBet *aOOBet_bf_new (int buffer);

/// Creates a new array from several elements.
/// Elements list must finish with NULL.
AOOBet *aOOBet_new_from (OOBet *e, ...);

/// Creates a new array from a C array. For example:
///   Arr *a = arr_new_c(3, (void *[]){"c", "d", "e"});
/// If 'size' is less than C array length, result is ok (only will be
/// used 'size' first elements); but if 'size' is greater, the result is
/// undetermined.
AOOBet *aOOBet_new_c (int size, OOBet **es);

/// Returns a new array with elements of 'this'.
AOOBet *aOOBet_copy (AOOBet *this);

///
int aOOBet_size (AOOBet *this);

/// Resturn the element at position ix.
OOBet *aOOBet_get (AOOBet *this, int ix);

/// Adds an element at the end of 'this'. 'e' will be freed by 'this'.
void aOOBet_push (AOOBet *this, OOBet *e);

/// Returns and removes the last element.
OOBet *aOOBet_pop (AOOBet *this);

/// Returns the las element.
OOBet *aOOBet_peek (AOOBet *this);

/// Sets the element at position ix.
void aOOBet_set (AOOBet *this, int ix, OOBet *e);

/// Inserts an element at position ix.
void aOOBet_insert (AOOBet *this, int ix, OOBet *e);

/// Removes an element at position ix. Buffer size of 'this' does not change.
void aOOBet_remove (AOOBet *this, int ix);

/// Adds pointer to elements of 'other' to 'this'.
void aOOBet_cat (AOOBet *this, AOOBet *other);

/// Inserts pointer to elements of 'other' at 'ix'
void aOOBet_insert_arr (AOOBet *this, int ix, AOOBet *other);

/// Removes elements between [begin-end). Buffer size of 'this' does not change.
void aOOBet_remove_range (AOOBet *this, int begin, int end);

/// Removes every element of 'this'.
void aOOBet_clear (AOOBet *this);

/// Reverses elements of 'this'.
void aOOBet_reverse (AOOBet *this);

/// Sorts 'this' ascendantly using the function 'greater' that returns '1'
/// if 'e1' > 'e2'.
void aOOBet_sort (AOOBet *this, int (*greater)(OOBet *e1, OOBet *e2));

/// aOOBet_shuflle remix 'this' elements. It should be used after calling
/// rnd_init() or sys_init().
void aOOBet_shuffle (AOOBet *this);

/// Returns '1' if every element of 'this' yields '1' with 'pred'.
int aOOBet_all (AOOBet *this, int (*pred)(OOBet *e));

/// Returns '1' if some element of 'this' yields '1' with 'pred'.
int aOOBet_any (AOOBet *this, int (*pred)(OOBet *e));

/// Returns the index of the first elements which returns '1'
/// with 'pred', or -1 if such element does not exist.
int aOOBet_index (AOOBet *this, int (*pred)(OOBet *e));

/// Returns the index of the last elements which returns '1'
/// with 'pred', or -1 if such element does not exist.
int aOOBet_last_index (AOOBet *this, int (*pred)(OOBet *e));

/// Returns the first element which pruduces '1' with 'pred' or 'tp_none'.
OOOBet *aOOBet_find(AOOBet *this, int (*pred)(OOBet *e));

/// Returns the last element which pruduces '1' with 'pred' or 'tp_none'.
OOOBet *aOOBet_find_last(AOOBet *this, int (*pred)(OOBet *e));

/// aOOBet_filter_in removes every element which returns '0' with 'pred'.
void aOOBet_filter_in (AOOBet *this, int (*pred)(OOBet *e));

/// Returns a new Arr with the n first elements of this.
/// If this has less elements than n, returs a copy of this.
AOOBet *aOOBet_take (AOOBet *this, int n);

/// Returns a new Arr with the first elements which return '1' with 'predicate'.
AOOBet *aOOBet_takef (AOOBet *this, int (*predicate)(OOBet *e));

/// Returns a new Arr with elements left after aOOBet_take.
AOOBet *aOOBet_drop (AOOBet *this, int n);

/// Returns a new Arr with elements left after aOOBet_takef.
AOOBet *aOOBet_dropf (AOOBet *this, int (*predicate)(OOBet *e));

/// Returns a new Arr with every element which returns '1' with 'pred'.
AOOBet *aOOBet_filter_to (AOOBet *this, int (*predicate)(OOBet *e));

/// Returns a new Arr with elements generated by converter.
Arr *aOOBet_map (AOOBet *this, void *(*converter)(OOBet *e));

/// Returns a new Arr whit the first element generated by conv1 and the rest
/// by conv2.
Arr *aOOBet_map2 (AOOBet *this, void *(*conv1)(OOBet *e), void *(*conv2)(OOBet *e));

/// Returns a new Arr mixing values of 'a1' and 'a2'. The size of the resultant
/// array is the less of 'a1' size and 'a2' size.
Arr *aOOBet_zip (AOOBet *a1, AOOBet *a2, void *(*converter)(OOBet *e1, OOBet *e2));

/// Returns a new Arr mixing values of 'a1', 'a2' and 'a3'. The size of the
/// resultant array is the less of 'a1' size, 'a2' size and 'a3' size.
Arr *aOOBet_zip3 (
  AOOBet *a1, AOOBet *a2, AOOBet *a3,
  void *(*conveter)(OOBet*e1, OOBet*e2, OOBet*e3)
);

/// Removes duplicates with function 'feq=1' and returns them in a new array.
/// It returns only the first duplicated element.
AOOBet *aOOBet_duplicates (AOOBet *this, int (feq)(OOBet *e1, OOBet *e2));

/// Returns this JSONized.
///   this: Container.
char *aOOBet_to_js (AOOBet *this);

/// Returns the container from its JSON representation.
///   js  : Container JSONized.
AOOBet *aOOBet_from_js (char *js);


//--// Not remove

#endif