name:                dummy3
version:             2018.11
github:              "githubuser/Dummy3"
license:             GPL-3
author:              "ºDeme"
maintainer:          "example@example.com"
copyright:           "2018 ºDeme"

extra-source-files:
- LICENSE

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/h#readme>

dependencies:
- base >= 4.7 && < 5
- libdmh
- time
- bytestring

library:
  source-dirs: src

executables:
  Dummy3:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dummy3

tests:
  h-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dummy3
