#!/bin/bash

PRG=YetiDoc
LIB=/dm/dmYeti/lib/libdmyeti/pack/libdmyeti.jar
#LIB=$LIB:/dm/dmYeti/lib/libmarketyeti/pack/libmarketyeti.jar

# ---------------------------------------------------------
YETI=/dm/dmYeti/tools/yeti.jar


case $1 in
project*)
  makedir () {
    if [ ! -e $NAME ] ; then mkdir $NAME ; fi
  }

  NAME=lib; makedir
  NAME=src; makedir
  NAME=classes; makedir
  NAME=pack; makedir
  NAME=tests; makedir
  NAME=tests/src; makedir
  NAME=tests/classes; makedir

  if [ ! -e src/start.yeti ]
  then
    echo 'module start;' > src/start.yeti
    echo '' >> src/start.yeti
    echo 'main args = (' >> src/start.yeti
    echo '  println (length args);' >> src/start.yeti
    echo ');' >> src/start.yeti
    echo '' >> src/start.yeti
    echo 'class Main' >> src/start.yeti
    echo '  static void main(String[] args)' >> src/start.yeti
    echo '    main (args)' >> src/start.yeti
    echo 'end;' >> src/start.yeti
  fi
  if [ ! -e tests/src/all.yeti ]
  then
    echo 'println "hello";' > tests/src/all.yeti
    echo '' >> tests/src/all.yeti
  fi
  ;;
c*)
  java -jar $YETI -cp $LIB -d classes src/*.yeti
  ;;
x*)
  java -jar $YETI -cp .:$LIB -d classes src/*.yeti
  java -cp $YETI:$LIB:classes Main
  ;;
pack*)
  java -jar $YETI -cp $LIB -d classes src/*.yeti
  if [ -e pack/tmp ]
  then
    rm -fR pack/tmp
  fi
  mkdir pack/tmp
  cd pack/tmp
  jar xvf $YETI
  LIBS=`echo $LIB | sed s/:/' '/g`
  for L in $LIBS
  do
    jar xvf $L
  done
  cp -fR ../../classes/* ./
  rm -fR META-INF
  mkdir META-INF
  echo 'Manifest-Version: 1.0' > META-INF/MANIFEST.MF
  echo 'Created-By: ºDeme' >> META-INF/MANIFEST.MF
  echo 'Main-Class: Main' >> META-INF/MANIFEST.MF
  echo ''>> META-INF/MANIFEST.MF
  jar cvfm ../$PRG.jar META-INF/MANIFEST.MF *
  cd ../..
  rm -fR pack/tmp
  ;;
tests*)
  java -jar $YETI -cp classes:$LIB -d tests/classes tests/src/*.yeti
  java -cp $YETI:$LIB:classes:tests/classes all
  ;;
*)
  echo $1: Unknown option
  ;;
esac
