#!/bin/bash

LIBS="dmjsBasic https://github.com/dedeme/dmjsBasic.git - \
      dmjsWidgets https://github.com/dedeme/dmjsWidgets.git - "

# Do not change --------------------------------------------

# Work from lib
# Variables: LIB, GIT, VAR
clone() {
  if [ -e tmp ]
  then
    rm -fR tmp
  fi
  mkdir tmp
  cd tmp

  if [ $VER == "-" ]
  then
    git clone $GIT
  else
    git clone --branch $VER $GIT
  fi

  cd ..
  if [ -e $LIB ]
  then
    rm -fR $LIB
  fi
  mv tmp/$LIB/src $LIB
  rm -fR tmp
}

if [ ! -e lib ]
then
  mkdir lib
fi

cd lib

LIB=""
GIT=""
VER=""
IX="0"
for GIT_LIB in $LIBS
do
  if [ $IX == "0" ]
  then
    LIB=$GIT_LIB
    IX="1"
  elif [ $IX == "1" ]
  then
    GIT=$GIT_LIB
    IX="2"
  else
    VER=$GIT_LIB
    clone
    IX="0"
  fi
done
