// Copyright 28-Dec-2021 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

/// Arr[Decision *].

#ifndef DATA_DECISION_ADECISION_H
  #define DATA_DECISION_ADECISION_H

#include "dmc/Arr.h"
#include "data/Decision/ODecision.h"

#include "data/Decision.h"

/// Arr[Decision *].
struct aDecision_ADecision {
  Decision **es; // Start elements.
  Decision **end; // End elements. (Elements are between 'es' (inclusive) and 'end'
              // exclusive.
  Decision **endbf; // End buffer.
};

/// Arr[Decision *].
typedef struct aDecision_ADecision ADecision;

/// Creates a new Array with buffer size of 15 elements.
ADecision *aDecision_new (void);

/// 'buffer' must be > 0.
ADecision *aDecision_bf_new (int buffer);

/// Creates a new array from several elements.
/// Elements list must finish with NULL.
ADecision *aDecision_new_from (Decision *e, ...);

/// Creates a new array from a C array. For example:
///   Arr *a = arr_new_c(3, (void *[]){"c", "d", "e"});
/// If 'size' is less than C array length, result is ok (only will be
/// used 'size' first elements); but if 'size' is greater, the result is
/// undetermined.
ADecision *aDecision_new_c (int size, Decision **es);

/// Returns a new array with elements of 'this'.
ADecision *aDecision_copy (ADecision *this);

///
int aDecision_size (ADecision *this);

/// Resturn the element at position ix.
Decision *aDecision_get (ADecision *this, int ix);

/// Adds an element at the end of 'this'. 'e' will be freed by 'this'.
void aDecision_push (ADecision *this, Decision *e);

/// Returns and removes the last element.
Decision *aDecision_pop (ADecision *this);

/// Returns the las element.
Decision *aDecision_peek (ADecision *this);

/// Sets the element at position ix.
void aDecision_set (ADecision *this, int ix, Decision *e);

/// Inserts an element at position ix.
void aDecision_insert (ADecision *this, int ix, Decision *e);

/// Removes an element at position ix. Buffer size of 'this' does not change.
void aDecision_remove (ADecision *this, int ix);

/// Adds pointer to elements of 'other' to 'this'.
void aDecision_cat (ADecision *this, ADecision *other);

/// Inserts pointer to elements of 'other' at 'ix'
void aDecision_insert_arr (ADecision *this, int ix, ADecision *other);

/// Removes elements between [begin-end). Buffer size of 'this' does not change.
void aDecision_remove_range (ADecision *this, int begin, int end);

/// Removes every element of 'this'.
void aDecision_clear (ADecision *this);

/// Reverses elements of 'this'.
void aDecision_reverse (ADecision *this);

/// Sorts 'this' ascendantly using the function 'greater' that returns '1'
/// if 'e1' > 'e2'.
void aDecision_sort (ADecision *this, int (*greater)(Decision *e1, Decision *e2));

/// aDecision_shuflle remix 'this' elements. It should be used after calling
/// rnd_init() or sys_init().
void aDecision_shuffle (ADecision *this);

/// Returns '1' if every element of 'this' yields '1' with 'pred'.
int aDecision_all (ADecision *this, int (*pred)(Decision *e));

/// Returns '1' if some element of 'this' yields '1' with 'pred'.
int aDecision_any (ADecision *this, int (*pred)(Decision *e));

/// Returns the index of the first elements which returns '1'
/// with 'pred', or -1 if such element does not exist.
int aDecision_index (ADecision *this, int (*pred)(Decision *e));

/// Returns the index of the last elements which returns '1'
/// with 'pred', or -1 if such element does not exist.
int aDecision_last_index (ADecision *this, int (*pred)(Decision *e));

/// Returns the first element which pruduces '1' with 'pred' or 'tp_none'.
ODecision *aDecision_find(ADecision *this, int (*pred)(Decision *e));

/// Returns the last element which pruduces '1' with 'pred' or 'tp_none'.
ODecision *aDecision_find_last(ADecision *this, int (*pred)(Decision *e));

/// aDecision_filter_in removes every element which returns '0' with 'pred'.
void aDecision_filter_in (ADecision *this, int (*pred)(Decision *e));

/// Returns a new Arr with the n first elements of this.
/// If this has less elements than n, returs a copy of this.
ADecision *aDecision_take (ADecision *this, int n);

/// Returns a new Arr with the first elements which return '1' with 'predicate'.
ADecision *aDecision_takef (ADecision *this, int (*predicate)(Decision *e));

/// Returns a new Arr with elements left after aDecision_take.
ADecision *aDecision_drop (ADecision *this, int n);

/// Returns a new Arr with elements left after aDecision_takef.
ADecision *aDecision_dropf (ADecision *this, int (*predicate)(Decision *e));

/// Returns a new Arr with every element which returns '1' with 'pred'.
ADecision *aDecision_filter_to (ADecision *this, int (*predicate)(Decision *e));

/// Returns a new Arr with elements generated by converter.
Arr *aDecision_map (ADecision *this, void *(*converter)(Decision *e));

/// Returns a new Arr whit the first element generated by conv1 and the rest
/// by conv2.
Arr *aDecision_map2 (ADecision *this, void *(*conv1)(Decision *e), void *(*conv2)(Decision *e));

/// Returns a new Arr mixing values of 'a1' and 'a2'. The size of the resultant
/// array is the less of 'a1' size and 'a2' size.
Arr *aDecision_zip (ADecision *a1, ADecision *a2, void *(*converter)(Decision *e1, Decision *e2));

/// Returns a new Arr mixing values of 'a1', 'a2' and 'a3'. The size of the
/// resultant array is the less of 'a1' size, 'a2' size and 'a3' size.
Arr *aDecision_zip3 (
  ADecision *a1, ADecision *a2, ADecision *a3,
  void *(*conveter)(Decision*e1, Decision*e2, Decision*e3)
);

/// Removes duplicates with function 'feq=1' and returns them in a new array.
/// It returns only the first duplicated element.
ADecision *aDecision_duplicates (ADecision *this, int (feq)(Decision *e1, Decision *e2));

/// Returns this JSONized.
///   this: Container.
char *aDecision_to_js (ADecision *this);

/// Returns the container from its JSON representation.
///   js  : Container JSONized.
ADecision *aDecision_from_js (char *js);


//--// Not remove

#endif