#!/bin/bash

LIBS="src,/dm/dmFay/lib/libdmfay/src"

# --------------------------------
# DON'T MODIFY
# --------------------------------

CMD=$1

case "$CMD" in
  init)
    echo "Unimplemented"
    ;;
  c)
    fay  -p --Wall --include $LIBS -o www/index.js src/Main.hs
    ;;
  x)
    echo "Unimplemented"
    ;;
  lang)
    echo "Unimplemented"
    ;;
  *)
    echo "Unkown command '$CMD'"
    ;;
esac

