#!/bin/bash

PRG=MMarket
LIB=/dm/dmYeti/lib/libdmyeti/pack/libdmyeti-v2020_04.jar

compileMain() {
  rm -fr classes
  java -jar $YETI -cp $LIB -doc doc -d classes \
    src/*.yeti \
    | sed -e 's/{/{\n  /g' | sed -e 's/} /\n}\n/g' | sed -e 's/, /,\n  /g'
  if [ -e resources ]
  then
    rm -fR resources
    cp -fR resources classes
  fi
}

compileTests() {
  java -jar $YETI -cp classes:$LIB -d tests/classes tests/src/all.yeti
  if [ -e tests/resources ]
  then
    rm -fR test/resources
    cp -fR tests/resources tests/classes
  fi
}

# ---------------------------------------------------------
YETI=/dm/dmJava/lib/yeti.jar
case $1 in
project)
  if [ ! -e "src" ] && [ ! -e "tests/src" ]
  then
    mkdir src
    mkdir classes
    mkdir pack
    mkdir tests
    mkdir tests/src
    mkdir tests/classes

    cd src
    echo "module "$PRG";" >> $PRG.yeti
    echo '' >> $PRG.yeti
    echo 'load es.dm.std;' >> $PRG.yeti
    echo '' >> $PRG.yeti
    echo 'class Main' >> $PRG.yeti
    echo '  static void main(String[] args)' >> $PRG.yeti
    echo '    println "here",' >> $PRG.yeti
    echo 'end;' >> $PRG.yeti
    cd ..

    cd tests/src
    echo 'load es.dm.std;' > all.yeti
    echo '' >> all.yeti
    echo 'println "here tests";' >> all.yeti
    cd ../..
  fi
  ;;
c)
  compileMain
  ;;
x)
  compileMain
  gnome-terminal -e "java -cp $YETI:$LIB:classes Main start"
  ;;
tests)
  compileMain
  compileTests
  java -cp $YETI:$LIB:classes:tests/classes all
  ;;
pack)
  compileMain
  mkdir pack/tmp
  cd pack/tmp
  jar xvf $YETI
  LIBS=`echo $LIB | sed s/:/' '/g`
  for L in $LIBS
  do
    jar xvf $L
  done
  cp -fR ../../classes/* ./
  rm -fR META-INF
  mkdir META-INF
  echo 'Manifest-Version: 1.0' > META-INF/MANIFEST.MF
  echo 'Created-By: ºDeme' >> META-INF/MANIFEST.MF
  echo 'Main-Class: Main' >> META-INF/MANIFEST.MF
  echo ''>> META-INF/MANIFEST.MF
  jar cvfm ../$PRG.jar META-INF/MANIFEST.MF *
  cd ../..
  rm -fR pack/tmp
  ;;
*)
  echo $1: Unknown option
  ;;
esac
