(* File generated by oci18n. *)

let es_dic = [
  {j|Accept|j}, {j|Aceptar|j};
  {j|Cancel|j}, {j|Cancelar|j};
  {j|Change Language to %0|j}, {j|Cambiar el lenguage a %0|j};
  {j|Change Password|j}, {j|Cambiar la contraseña|j};
  {j|Check gray squares|j}, {j|Marcar los cuadrados grises|j};
  {j|Click %0 to continue.|j}, {j|Hacer click %0 para continuar.|j};
  {j|Confirm password|j}, {j|Confirmar la contraseña|j};
  {j|Confirm password is missing|j}, {j|Falta la confirmación de la contraseña|j};
  {j|Current password|j}, {j|Contraseña actual|j};
  {j|Current password is missing|j}, {j|Falta indicar la contraseña actual|j};
  {j|Fail trying to change password|j}, {j|Fallo intentando cambiar la contraseña|j};
  {j|Grey squares checks are wrong|j}, {j|Las casillas grises están mal marcadas|j};
  {j|here|j}, {j|aquí|j};
  {j|Keep connected|j}, {j|Mantenerse conectado|j};
  {j|Libraries|j}, {j|Librerías|j};
  {j|Login|j}, {j|Identificación|j};
  {j|Logout-message|j}, {j|<p>%0 ha terminado.</p><p><b>¡Hasta pronto!</b></p>|j};
  {j|Name|j}, {j|Nombre|j};
  {j|New password|j}, {j|Nueva contraseña|j};
  {j|New password and confirm password do not match|j}, {j|La nueva contraseña y su confirmación no coinciden|j};
  {j|New password is missing|j}, {j|Falta indicar la nueva contraseña|j};
  {j|Password|j}, {j|Contraseña|j};
  {j|Password is missing|j}, {j|Falta indicar la contraseña|j};
  {j|Password successfully changed|j}, {j|La contraseña se cambió correctamente|j};
  {j|Path|j}, {j|Ruta|j};
  {j|Session is expired.|j}, {j|La sesión ha expirado.|j};
  {j|There is no library|j}, {j|No hay ninguna librería|j};
  {j|User|j}, {j|Usuario|j};
  {j|User name is missing|j}, {j|Falta indicar el nombre del usuario|j};
  {j|Writer|j}, {j|Escritor|j};
  {j|Wrong password|j}, {j|La contraseña es incorrecta|j};
]

let en_dic = [
  {j|Accept|j}, {j|Accept|j};
  {j|Cancel|j}, {j|Cancel|j};
  {j|Change Language to %0|j}, {j|Change Language to %0|j};
  {j|Change Password|j}, {j|Change Password|j};
  {j|Check gray squares|j}, {j|Check gray squares|j};
  {j|Click %0 to continue.|j}, {j|Click %0 to continue.|j};
  {j|Confirm password|j}, {j|Confirm password|j};
  {j|Confirm password is missing|j}, {j|'Confirm password' is missing|j};
  {j|Current password|j}, {j|Current password|j};
  {j|Current password is missing|j}, {j|'Current password' is missing|j};
  {j|Fail trying to change password|j}, {j|Fail trying to change password|j};
  {j|Grey squares checks are wrong|j}, {j|Grey squares checks are wrong|j};
  {j|here|j}, {j|here|j};
  {j|Keep connected|j}, {j|Keep connected|j};
  {j|Libraries|j}, {j|Libraries|j};
  {j|Login|j}, {j|Login|j};
  {j|Logout-message|j}, {j|<p>%0 has finished.</p><p><b>Good by!</b></p>|j};
  {j|Name|j}, {j|Name|j};
  {j|New password|j}, {j|New password|j};
  {j|New password and confirm password do not match|j}, {j|New password and confirm password do not match|j};
  {j|New password is missing|j}, {j|'New password' is missing|j};
  {j|Password|j}, {j|Password|j};
  {j|Password is missing|j}, {j|Password is missing|j};
  {j|Password successfully changed|j}, {j|Password successfully changed|j};
  {j|Path|j}, {j|Path|j};
  {j|Session is expired.|j}, {j|Session is expired.|j};
  {j|There is no library|j}, {j|There is no library|j};
  {j|User|j}, {j|User|j};
  {j|User name is missing|j}, {j|User name is missing|j};
  {j|Writer|j}, {j|Writer|j};
  {j|Wrong password|j}, {j|Wrong password|j};
]

let dic = ref (Dic.mk ())

let en () = dic := Dic.of_it (It.of_list en_dic)

let es () = dic := Dic.of_it (It.of_list es_dic)

let i18 key = match Dic.get key !dic with
| None -> key
| Some s -> s

let i18f fmt l = Txt.(
let a = Array.of_list l in
let fmt = mk (i18 fmt) in
let fn tx i =
replace ("%" ^ string_of_int i) a.(i) tx |> mk
in
It.reduce fmt fn (It.range 0 (Array.length a)) |> replace "%%" "%"
)

