(* File generated by oci18n. *)

let es_dic = [
  {j|'%0' can not be read|j}, {j|'%0' no puede ser leido|j};
  {j|'%0' is an empty file|j}, {j|'%0' es un archivo vacío|j};
  {j|Accept|j}, {j|Aceptar|j};
  {j|All the data will be replaced|j}, {j|¡ATENCIÓN!. Todos los datos serán reemplazados.\n¿Continuar?|j};
  {j|Backs|j}, {j|Copias|j};
  {j|Backup file is missing|j}, {j|No se ha indicado el archivo de backup|j};
  {j|Backups|j}, {j|Copias de seguridad|j};
  {j|Cancel|j}, {j|Cancelar|j};
  {j|Change language to|j}, {j|Cambiar lenguaje a|j};
  {j|Change password|j}, {j|Cambiar contraseña|j};
  {j|Check gray squares|j}, {j|Marcar los cuadrados grises|j};
  {j|Clear|j}, {j|Eliminar|j};
  {j|Clear trash?|j}, {j|¿Vaciar la papelera?|j};
  {j|Click %0 to continue.|j}, {j|Hacer click %0 para continuar.|j};
  {j|Confirm password|j}, {j|Confirmar la contraseña|j};
  {j|Confirm password is missing|j}, {j|Falta la confirmación de la contraseña|j};
  {j|Current password|j}, {j|Contraseña actual|j};
  {j|Current password is missing|j}, {j|Falta indicar la contraseña actual|j};
  {j|Download|j}, {j|Descarga|j};
  {j|Fail trying to change password|j}, {j|Fallo intentando cambiar la contraseña|j};
  {j|Fail unzipping backup.|j}, {j|Fallo descomprimiendo la copia de seguridad.|j};
  {j|File has not data|j}, {j|El archivo no tiene datos|j};
  {j|File is not a valid backup.|j}, {j|El archivo no es una copia de seguridad válida.|j};
  {j|Grey squares checks are wrong|j}, {j|Las casillas grises están mal marcadas|j};
  {j|here|j}, {j|aquí|j};
  {j|Keep connected|j}, {j|Mantenerse conectado|j};
  {j|Login|j}, {j|Identificación|j};
  {j|Logout-message|j}, {j|<p>%0 ha terminado.</p><p><b>¡Hasta pronto!</b></p>|j};
  {j|Make backup|j}, {j|Hacer copia|j};
  {j|New password|j}, {j|Nueva contraseña|j};
  {j|New password and confirm password do not match|j}, {j|La nueva contraseña y su confirmación no coinciden|j};
  {j|New password is missing|j}, {j|Falta indicar la nueva contraseña|j};
  {j|Only one file can be selected|j}, {j|Sólo se puede seleccionar un archivo|j};
  {j|Password|j}, {j|Contraseña|j};
  {j|Password is missing|j}, {j|Falta indicar la contraseña|j};
  {j|Password successfully changed|j}, {j|La contraseña se cambió correctamente|j};
  {j|Reader|j}, {j|Lector|j};
  {j|Restore|j}, {j|Restauración|j};
  {j|Restore backup|j}, {j|Restaurar copia|j};
  {j|Session is expired.|j}, {j|La sesión ha expirado.|j};
  {j|Settings|j}, {j|Configuración|j};
  {j|Trash|j}, {j|Papelera|j};
  {j|Unexpected fail.|j}, {j|Fallo inesperado.|j};
  {j|User|j}, {j|Usuario|j};
  {j|User name is missing|j}, {j|Falta indicar el nombre del usuario|j};
  {j|Writer|j}, {j|Escritor|j};
  {j|Wrong password|j}, {j|La contraseña es incorrecta|j};
]

let en_dic = [
  {j|'%0' can not be read|j}, {j|'%0' can not be read|j};
  {j|'%0' is an empty file|j}, {j|'%0' is an empty file|j};
  {j|Accept|j}, {j|Accept|j};
  {j|All the data will be replaced|j}, {j|ATENTION!: All the data will be replaced.\nContinue?|j};
  {j|Backs|j}, {j|Backups|j};
  {j|Backup file is missing|j}, {j|Backup file is missin|j};
  {j|Backups|j}, {j|Backups|j};
  {j|Cancel|j}, {j|Cancel|j};
  {j|Change language to|j}, {j|Change language to|j};
  {j|Change password|j}, {j|Change password|j};
  {j|Check gray squares|j}, {j|Check gray squares|j};
  {j|Clear|j}, {j|Clear|j};
  {j|Clear trash?|j}, {j|Clear trash?|j};
  {j|Click %0 to continue.|j}, {j|Click %0 to continue.|j};
  {j|Confirm password|j}, {j|Confirm password|j};
  {j|Confirm password is missing|j}, {j|'Confirm password' is missing|j};
  {j|Current password|j}, {j|Current password|j};
  {j|Current password is missing|j}, {j|'Current password' is missing|j};
  {j|Download|j}, {j|Download|j};
  {j|Fail trying to change password|j}, {j|Fail trying to change password|j};
  {j|Fail unzipping backup.|j}, {j|Fail unzipping backup.|j};
  {j|File has not data|j}, {j|File has not data|j};
  {j|File is not a valid backup.|j}, {j|File is not a valid backup.|j};
  {j|Grey squares checks are wrong|j}, {j|Grey squares checks are wrong|j};
  {j|here|j}, {j|here|j};
  {j|Keep connected|j}, {j|Keep connected|j};
  {j|Login|j}, {j|Login|j};
  {j|Logout-message|j}, {j|<p>%0 has finished.</p><p><b>Good by!</b></p>|j};
  {j|Make backup|j}, {j|Make backup|j};
  {j|New password|j}, {j|New password|j};
  {j|New password and confirm password do not match|j}, {j|New password and confirm password do not match|j};
  {j|New password is missing|j}, {j|'New password' is missing|j};
  {j|Only one file can be selected|j}, {j|Only one file can be selected|j};
  {j|Password|j}, {j|Password|j};
  {j|Password is missing|j}, {j|Password is missing|j};
  {j|Password successfully changed|j}, {j|Password successfully changed|j};
  {j|Reader|j}, {j|Reader|j};
  {j|Restore|j}, {j|Restore|j};
  {j|Restore backup|j}, {j|Restore backup|j};
  {j|Session is expired.|j}, {j|Session is expired.|j};
  {j|Settings|j}, {j|Settings|j};
  {j|Trash|j}, {j|Trash|j};
  {j|Unexpected fail.|j}, {j|Unexpected fail.|j};
  {j|User|j}, {j|User|j};
  {j|User name is missing|j}, {j|User name is missing|j};
  {j|Writer|j}, {j|Writer|j};
  {j|Wrong password|j}, {j|Wrong password|j};
]

let dic = ref (Dic.mk ())

let en () = dic := Dic.of_it (It.of_list en_dic)

let es () = dic := Dic.of_it (It.of_list es_dic)

let i18 key = match Dic.get key !dic with
| None -> key
| Some s -> s

let i18f fmt l = Txt.(
let a = Array.of_list l in
let fmt = mk (i18 fmt) in
let fn tx i =
replace ("%" ^ string_of_int i) a.(i) tx |> mk
in
It.reduce fmt fn (It.range 0 (Array.length a)) |> replace "%%" "%"
)

