#!/bin/bash
if [  -e lib/liblocalcompilation ]
then
  rm -fr lib/liblocalcompilation
fi

if [ ! -e lib/liblocal ]
then
  mkdir -p lib/liblocal
fi

if [ ! -e lib/liblocal/include ]
then
  ln -f -s ../../../include lib/liblocal/include
fi

if [ ! -e lib/liblocal/liblocal.a ]
then
ln -f -s ../../../lib/liblocalcompilation/liblocalcompilation.a \
         lib/liblocal/liblocal.a
fi

if [ ! -e lib/libdmc ]
then
ln -f -s ../../lib/libdmc lib/libdmc
fi
if [ ! -e lib/match ]
then
ln -f -s ../../lib/libmatch lib/libmatch
fi

