#!/bin/bash

GIT1="--branch 202106 https://github.com/dedeme/jshxlib.git"
GIT2="--branch v202006 https://github.com/dedeme/wghxlib.git"

if [ ! -e lib ]
then
  mkdir lib
fi
cd lib

if [ -e tmp ]
then
  rm -fR tmp
fi
mkdir tmp
cd tmp
git clone $GIT1
git clone $GIT2
cd ..

if [ -e dm ]
then
  rm -fR dm
fi
mv tmp/jshxlib/src/dm dm
cp -r tmp/wghxlib/src/dm ./
rm -fR tmp


